language: perl
os:
  - linux
  # - osx

perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  # - "5.12"

before_install:
  cpanm -qn Devel::Cover::Report::Coveralls Test::Script Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Carp LWP::Protocol::https JSON::XS Test::LWP::UserAgent

install:
  - cpanm -q --installdeps --notest .

script:
  perl Makefile.PL && make && cover -test -report coveralls
